spring:
  datasource:
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE'
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
server:
  port: 8081
springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger.html